### ISSUE TITLE
[BUG] impossible to develop

### ISSUE THREAD

**Issue by exactmultiple3425** [guibulator/gatsby-starter-i18next-ssr#1]
When the component is refreshed, the following error pops up.

TypeError: Cannot read property 'componentChunkName' of undefined

Gatsby version: 2.1.19

![Screenshot 2019-03-19 at 10 41 07 AM](https://user-images.githubusercontent.com/8279406/54576568-b90dfd00-4a33-11e9-9622-1dcc95cf4286.png)

**Comment by guibulator** [comment]
I just updated the code. Thanks.
